# Use postgres/example user/password credentials
version: '3.8'

services:
  postgres:
    image: postgres
    container_name: gestao_pg
    environment:
      POSTGRES_DB: gestao_db        
      POSTGRES_USER: admin         
      POSTGRES_PASSWORD: admin  
    ports:
      - "5432:5432"   
